//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeCertApp_WebAPi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificationRequest
    {
        public System.DateTime RequestDate { get; set; }
        public int RequestByUserId { get; set; }
        public int RequestForCertificationId { get; set; }
        public string Remarks { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreationTS { get; set; }
        public int LastModdifiedbyUserId { get; set; }
        public System.DateTime LastModdifiedTS { get; set; }
        public Nullable<int> amount { get; set; }
        public string IRA { get; set; }
        public string quarter { get; set; }
        public Nullable<int> CertificationCategory { get; set; }
        public int RequestId { get; set; }
        public string ApproverRemarks { get; set; }
        public string Status { get; set; }
    }
}
